// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BatchHealthCheckAll() {
  return window['go']['main']['App']['BatchHealthCheckAll']();
}

export function BatchUpdateSettings(arg1) {
  return window['go']['main']['App']['BatchUpdateSettings'](arg1);
}

export function CheckPortAvailable(arg1) {
  return window['go']['main']['App']['CheckPortAvailable'](arg1);
}

export function ClearClaudeRoutingOverride() {
  return window['go']['main']['App']['ClearClaudeRoutingOverride']();
}

export function ClearNegativeHitCache(arg1) {
  return window['go']['main']['App']['ClearNegativeHitCache'](arg1);
}

export function ClearPrivacyExactSecrets(arg1) {
  return window['go']['main']['App']['ClearPrivacyExactSecrets'](arg1);
}

export function CreateEndpointRecord(arg1) {
  return window['go']['main']['App']['CreateEndpointRecord'](arg1);
}

export function CreateModelPricing(arg1) {
  return window['go']['main']['App']['CreateModelPricing'](arg1);
}

export function CreatePrivacyExactSecret(arg1) {
  return window['go']['main']['App']['CreatePrivacyExactSecret'](arg1);
}

export function CreatePrivacyRule(arg1) {
  return window['go']['main']['App']['CreatePrivacyRule'](arg1);
}

export function CreateUpstreamAccount(arg1) {
  return window['go']['main']['App']['CreateUpstreamAccount'](arg1);
}

export function DeleteEndpointRecord(arg1) {
  return window['go']['main']['App']['DeleteEndpointRecord'](arg1);
}

export function DeleteModelPricing(arg1) {
  return window['go']['main']['App']['DeleteModelPricing'](arg1);
}

export function DeletePrivacyExactSecret(arg1) {
  return window['go']['main']['App']['DeletePrivacyExactSecret'](arg1);
}

export function DeletePrivacyRule(arg1) {
  return window['go']['main']['App']['DeletePrivacyRule'](arg1);
}

export function DeleteUpstreamAccount(arg1) {
  return window['go']['main']['App']['DeleteUpstreamAccount'](arg1);
}

export function EnableAutomaticAccountSelection() {
  return window['go']['main']['App']['EnableAutomaticAccountSelection']();
}

export function ExchangeChatGPTOAuthCallback(arg1) {
  return window['go']['main']['App']['ExchangeChatGPTOAuthCallback'](arg1);
}

export function ExportPrivacyRules() {
  return window['go']['main']['App']['ExportPrivacyRules']();
}

export function GenerateChatGPTOAuthLink() {
  return window['go']['main']['App']['GenerateChatGPTOAuthLink']();
}

export function GetAllSettings() {
  return window['go']['main']['App']['GetAllSettings']();
}

export function GetClaudeRoutingState() {
  return window['go']['main']['App']['GetClaudeRoutingState']();
}

export function GetCodexModelCatalog() {
  return window['go']['main']['App']['GetCodexModelCatalog']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetConnectionActivityChart(arg1) {
  return window['go']['main']['App']['GetConnectionActivityChart'](arg1);
}

export function GetEndpointCosts() {
  return window['go']['main']['App']['GetEndpointCosts']();
}

export function GetEndpointHealthChart() {
  return window['go']['main']['App']['GetEndpointHealthChart']();
}

export function GetEndpointRecord(arg1) {
  return window['go']['main']['App']['GetEndpointRecord'](arg1);
}

export function GetEndpointRecords() {
  return window['go']['main']['App']['GetEndpointRecords']();
}

export function GetEndpointStorageStatus() {
  return window['go']['main']['App']['GetEndpointStorageStatus']();
}

export function GetEndpoints() {
  return window['go']['main']['App']['GetEndpoints']();
}

export function GetLatestAccountScheduleSnapshot() {
  return window['go']['main']['App']['GetLatestAccountScheduleSnapshot']();
}

export function GetLatestEndpointScheduleSnapshot() {
  return window['go']['main']['App']['GetLatestEndpointScheduleSnapshot']();
}

export function GetLogStreamStatus() {
  return window['go']['main']['App']['GetLogStreamStatus']();
}

export function GetMigrationStatus() {
  return window['go']['main']['App']['GetMigrationStatus']();
}

export function GetModelPricing(arg1) {
  return window['go']['main']['App']['GetModelPricing'](arg1);
}

export function GetModelPricingStorageStatus() {
  return window['go']['main']['App']['GetModelPricingStorageStatus']();
}

export function GetModelPricings() {
  return window['go']['main']['App']['GetModelPricings']();
}

export function GetPortInfo() {
  return window['go']['main']['App']['GetPortInfo']();
}

export function GetPrivacyRuntimeStats() {
  return window['go']['main']['App']['GetPrivacyRuntimeStats']();
}

export function GetPrivacySettings() {
  return window['go']['main']['App']['GetPrivacySettings']();
}

export function GetProxyURL() {
  return window['go']['main']['App']['GetProxyURL']();
}

export function GetRecentLogs(arg1) {
  return window['go']['main']['App']['GetRecentLogs'](arg1);
}

export function GetRequestTrendChart(arg1) {
  return window['go']['main']['App']['GetRequestTrendChart'](arg1);
}

export function GetRequests(arg1) {
  return window['go']['main']['App']['GetRequests'](arg1);
}

export function GetResponseTimeChart(arg1) {
  return window['go']['main']['App']['GetResponseTimeChart'](arg1);
}

export function GetSetting(arg1, arg2) {
  return window['go']['main']['App']['GetSetting'](arg1, arg2);
}

export function GetSettingCategories() {
  return window['go']['main']['App']['GetSettingCategories']();
}

export function GetSettingsByCategory(arg1) {
  return window['go']['main']['App']['GetSettingsByCategory'](arg1);
}

export function GetSettingsStorageStatus() {
  return window['go']['main']['App']['GetSettingsStorageStatus']();
}

export function GetSystemStatus() {
  return window['go']['main']['App']['GetSystemStatus']();
}

export function GetTokenUsage() {
  return window['go']['main']['App']['GetTokenUsage']();
}

export function GetUpstreamAccountCredential(arg1) {
  return window['go']['main']['App']['GetUpstreamAccountCredential'](arg1);
}

export function GetUpstreamAccounts() {
  return window['go']['main']['App']['GetUpstreamAccounts']();
}

export function GetUsageStats(arg1) {
  return window['go']['main']['App']['GetUsageStats'](arg1);
}

export function GetUsageSummary(arg1, arg2) {
  return window['go']['main']['App']['GetUsageSummary'](arg1, arg2);
}

export function ImportPrivacyPreset(arg1) {
  return window['go']['main']['App']['ImportPrivacyPreset'](arg1);
}

export function ImportPrivacySecretCandidate(arg1) {
  return window['go']['main']['App']['ImportPrivacySecretCandidate'](arg1);
}

export function IsProxyRunning() {
  return window['go']['main']['App']['IsProxyRunning']();
}

export function ListPrivacyExactSecrets() {
  return window['go']['main']['App']['ListPrivacyExactSecrets']();
}

export function ListPrivacyPresets() {
  return window['go']['main']['App']['ListPrivacyPresets']();
}

export function ListPrivacyRules() {
  return window['go']['main']['App']['ListPrivacyRules']();
}

export function ListPrivacySecretImportCandidates() {
  return window['go']['main']['App']['ListPrivacySecretImportCandidates']();
}

export function MergeDefaultCodexModelCatalog() {
  return window['go']['main']['App']['MergeDefaultCodexModelCatalog']();
}

export function MoveUpstreamAccountToTier(arg1, arg2) {
  return window['go']['main']['App']['MoveUpstreamAccountToTier'](arg1, arg2);
}

export function PinUpstreamAccountSelection(arg1) {
  return window['go']['main']['App']['PinUpstreamAccountSelection'](arg1);
}

export function RefreshUpstreamAccountProfile(arg1) {
  return window['go']['main']['App']['RefreshUpstreamAccountProfile'](arg1);
}

export function ReorderPrivacyRules(arg1) {
  return window['go']['main']['App']['ReorderPrivacyRules'](arg1);
}

export function ResetCategorySettings(arg1) {
  return window['go']['main']['App']['ResetCategorySettings'](arg1);
}

export function ResetCodexModelCatalog() {
  return window['go']['main']['App']['ResetCodexModelCatalog']();
}

export function RetryStartupMigration() {
  return window['go']['main']['App']['RetryStartupMigration']();
}

export function SaveCodexModelCatalog(arg1) {
  return window['go']['main']['App']['SaveCodexModelCatalog'](arg1);
}

export function SetClaudeRoutingOverride(arg1) {
  return window['go']['main']['App']['SetClaudeRoutingOverride'](arg1);
}

export function SetDefaultModelPricing(arg1) {
  return window['go']['main']['App']['SetDefaultModelPricing'](arg1);
}

export function SetEndpointAutoSchedule(arg1, arg2) {
  return window['go']['main']['App']['SetEndpointAutoSchedule'](arg1, arg2);
}

export function SetEndpointAvailability(arg1, arg2) {
  return window['go']['main']['App']['SetEndpointAvailability'](arg1, arg2);
}

export function SetEndpointPriority(arg1, arg2) {
  return window['go']['main']['App']['SetEndpointPriority'](arg1, arg2);
}

export function SetGroupActiveAccount(arg1, arg2) {
  return window['go']['main']['App']['SetGroupActiveAccount'](arg1, arg2);
}

export function StartLogStream() {
  return window['go']['main']['App']['StartLogStream']();
}

export function StopLogStream() {
  return window['go']['main']['App']['StopLogStream']();
}

export function SwapUpstreamAccountGroups(arg1, arg2) {
  return window['go']['main']['App']['SwapUpstreamAccountGroups'](arg1, arg2);
}

export function TestPrivacyRules(arg1) {
  return window['go']['main']['App']['TestPrivacyRules'](arg1);
}

export function TestUpstreamAccount(arg1) {
  return window['go']['main']['App']['TestUpstreamAccount'](arg1);
}

export function ToggleUpstreamAccount(arg1, arg2) {
  return window['go']['main']['App']['ToggleUpstreamAccount'](arg1, arg2);
}

export function TriggerHealthCheck(arg1) {
  return window['go']['main']['App']['TriggerHealthCheck'](arg1);
}

export function UpdateEndpointRecord(arg1, arg2) {
  return window['go']['main']['App']['UpdateEndpointRecord'](arg1, arg2);
}

export function UpdateModelPricing(arg1, arg2) {
  return window['go']['main']['App']['UpdateModelPricing'](arg1, arg2);
}

export function UpdatePreferredPort(arg1) {
  return window['go']['main']['App']['UpdatePreferredPort'](arg1);
}

export function UpdatePrivacyExactSecret(arg1, arg2) {
  return window['go']['main']['App']['UpdatePrivacyExactSecret'](arg1, arg2);
}

export function UpdatePrivacyRule(arg1, arg2) {
  return window['go']['main']['App']['UpdatePrivacyRule'](arg1, arg2);
}

export function UpdatePrivacySettings(arg1) {
  return window['go']['main']['App']['UpdatePrivacySettings'](arg1);
}

export function UpdateSetting(arg1) {
  return window['go']['main']['App']['UpdateSetting'](arg1);
}

export function UpdateUpstreamAccount(arg1, arg2) {
  return window['go']['main']['App']['UpdateUpstreamAccount'](arg1, arg2);
}
