// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {logging} from '../models';

export function ActivateGroup(arg1:string):Promise<void>;

export function BatchHealthCheckAll():Promise<main.BatchHealthCheckResult>;

export function BatchUpdateSettings(arg1:main.BatchUpdateSettingsInput):Promise<void>;

export function CheckPortAvailable(arg1:number):Promise<boolean>;

export function ClearClaudeRoutingOverride():Promise<main.ClaudeRoutingState>;

export function ClearNegativeHitCache(arg1:string):Promise<void>;

export function ClearPrivacyExactSecrets(arg1:string):Promise<void>;

export function CreateEndpointRecord(arg1:main.CreateEndpointInput):Promise<void>;

export function CreateModelPricing(arg1:main.CreateModelPricingInput):Promise<void>;

export function CreatePrivacyExactSecret(arg1:main.PrivacyExactSecretInput):Promise<main.PrivacyExactSecretInfo>;

export function CreatePrivacyRule(arg1:main.PrivacyRuleInput):Promise<main.PrivacyRuleInfo>;

export function CreateUpstreamAccount(arg1:main.CreateUpstreamAccountInput):Promise<void>;

export function DeleteEndpointRecord(arg1:string):Promise<void>;

export function DeleteModelPricing(arg1:string):Promise<void>;

export function DeletePrivacyExactSecret(arg1:number):Promise<void>;

export function DeletePrivacyRule(arg1:number):Promise<void>;

export function DeleteUpstreamAccount(arg1:number):Promise<void>;

export function EnableAutomaticAccountSelection():Promise<main.EnableAutomaticAccountSelectionResult>;

export function ExchangeChatGPTOAuthCallback(arg1:main.ExchangeChatGPTOAuthCallbackInput):Promise<main.ExchangeChatGPTOAuthCallbackResult>;

export function ExportPrivacyRules():Promise<main.PrivacyRuleExportInfo>;

export function GenerateChatGPTOAuthLink():Promise<main.GenerateChatGPTOAuthLinkResult>;

export function GetAllSettings():Promise<Array<main.SettingInfo>>;

export function GetChannels():Promise<Array<main.ChannelInfo>>;

export function GetClaudeRoutingState():Promise<main.ClaudeRoutingState>;

export function GetCodexModelCatalog():Promise<main.CodexModelCatalogInfo>;

export function GetConfig():Promise<main.ConfigInfo>;

export function GetConnectionActivityChart(arg1:number):Promise<Array<main.ChartDataPoint>>;

export function GetEndpointCosts():Promise<Array<main.EndpointCostItem>>;

export function GetEndpointHealthChart():Promise<main.EndpointHealthData>;

export function GetEndpointRecord(arg1:string):Promise<main.EndpointRecordInfo>;

export function GetEndpointRecords():Promise<Array<main.EndpointRecordInfo>>;

export function GetEndpointStorageStatus():Promise<main.EndpointStorageStatus>;

export function GetEndpoints():Promise<Array<main.EndpointInfo>>;

export function GetEndpointsByChannel(arg1:string):Promise<Array<main.EndpointRecordInfo>>;

export function GetGroups():Promise<Array<main.GroupInfo>>;

export function GetKeysOverview():Promise<main.KeysOverviewResult>;

export function GetLatestAccountScheduleSnapshot():Promise<main.LatestAccountScheduleSnapshotInfo>;

export function GetLatestEndpointScheduleSnapshot():Promise<main.LatestEndpointScheduleSnapshotInfo>;

export function GetLogStreamStatus():Promise<boolean>;

export function GetModelPricing(arg1:string):Promise<main.ModelPricingInfo>;

export function GetModelPricingStorageStatus():Promise<main.ModelPricingStorageStatus>;

export function GetModelPricings():Promise<Array<main.ModelPricingInfo>>;

export function GetPortInfo():Promise<main.PortInfo>;

export function GetPrivacyRuntimeStats():Promise<main.PrivacyRuntimeStatsInfo>;

export function GetPrivacySettings():Promise<main.PrivacySettingsInfo>;

export function GetProxyURL():Promise<string>;

export function GetRecentLogs(arg1:number):Promise<Array<logging.LogEntry>>;

export function GetRequestTrendChart(arg1:number):Promise<Array<main.ChartDataPoint>>;

export function GetRequests(arg1:main.RequestQueryParams):Promise<main.RequestListResult>;

export function GetResponseTimeChart(arg1:number):Promise<Array<main.ChartDataPoint>>;

export function GetSetting(arg1:string,arg2:string):Promise<main.SettingInfo>;

export function GetSettingCategories():Promise<Array<main.CategoryInfo>>;

export function GetSettingsByCategory(arg1:string):Promise<Array<main.SettingInfo>>;

export function GetSettingsStorageStatus():Promise<main.SettingsStorageStatus>;

export function GetSystemStatus():Promise<main.SystemStatus>;

export function GetTokenUsage():Promise<main.TokenUsageData>;

export function GetUpstreamAccountCredential(arg1:number):Promise<main.UpstreamAccountCredentialInfo>;

export function GetUpstreamAccounts():Promise<Array<main.UpstreamAccountInfo>>;

export function GetUsageStats(arg1:main.UsageStatsQueryParams):Promise<main.UsageStatsData>;

export function GetUsageSummary(arg1:string,arg2:string):Promise<main.UsageSummary>;

export function ImportPrivacyPreset(arg1:string):Promise<Array<main.PrivacyRuleInfo>>;

export function ImportPrivacySecretCandidate(arg1:main.ImportPrivacySecretCandidateInput):Promise<main.PrivacyExactSecretInfo>;

export function IsProxyRunning():Promise<boolean>;

export function ListPrivacyExactSecrets():Promise<Array<main.PrivacyExactSecretInfo>>;

export function ListPrivacyPresets():Promise<Array<main.PrivacyPresetInfo>>;

export function ListPrivacyRules():Promise<Array<main.PrivacyRuleInfo>>;

export function ListPrivacySecretImportCandidates():Promise<Array<main.PrivacySecretImportCandidateInfo>>;

export function MergeDefaultCodexModelCatalog():Promise<main.CodexModelCatalogInfo>;

export function MoveUpstreamAccountToTier(arg1:number,arg2:string):Promise<main.MoveUpstreamAccountToTierResult>;

export function PauseGroup(arg1:string):Promise<void>;

export function PinUpstreamAccountSelection(arg1:number):Promise<main.PinUpstreamAccountSelectionResult>;

export function RefreshUpstreamAccountProfile(arg1:number):Promise<main.RefreshUpstreamAccountProfileResult>;

export function ReorderPrivacyRules(arg1:Array<main.PrivacyRuleOrderInput>):Promise<void>;

export function ResetCategorySettings(arg1:string):Promise<void>;

export function ResetCodexModelCatalog():Promise<main.CodexModelCatalogInfo>;

export function ResumeGroup(arg1:string):Promise<void>;

export function SaveCodexModelCatalog(arg1:main.SaveCodexModelCatalogInput):Promise<main.CodexModelCatalogInfo>;

export function SetClaudeRoutingOverride(arg1:main.SetClaudeRoutingOverrideInput):Promise<main.ClaudeRoutingState>;

export function SetDefaultModelPricing(arg1:string):Promise<void>;

export function SetEndpointPriority(arg1:string,arg2:number):Promise<void>;

export function SetGroupActiveAccount(arg1:string,arg2:number):Promise<main.SetGroupActiveAccountResult>;

export function StartLogStream():Promise<void>;

export function StopLogStream():Promise<void>;

export function SwapUpstreamAccountGroups(arg1:string,arg2:string):Promise<main.SwapUpstreamAccountGroupsResult>;

export function SwitchKey(arg1:string,arg2:string,arg3:number):Promise<main.SwitchKeyResult>;

export function TestPrivacyRules(arg1:main.PrivacyRuleTestInput):Promise<main.PrivacyRuleTestResult>;

export function TestUpstreamAccount(arg1:number):Promise<main.TestUpstreamAccountResult>;

export function ToggleEndpointRecord(arg1:string,arg2:boolean):Promise<void>;

export function ToggleUpstreamAccount(arg1:number,arg2:boolean):Promise<void>;

export function TriggerHealthCheck(arg1:string):Promise<void>;

export function UpdateEndpointRecord(arg1:string,arg2:main.CreateEndpointInput):Promise<void>;

export function UpdateModelPricing(arg1:string,arg2:main.CreateModelPricingInput):Promise<void>;

export function UpdatePreferredPort(arg1:number):Promise<void>;

export function UpdatePrivacyExactSecret(arg1:number,arg2:main.PrivacyExactSecretInput):Promise<main.PrivacyExactSecretInfo>;

export function UpdatePrivacyRule(arg1:number,arg2:main.PrivacyRuleInput):Promise<main.PrivacyRuleInfo>;

export function UpdatePrivacySettings(arg1:main.PrivacySettingsInput):Promise<main.PrivacySettingsInfo>;

export function UpdateSetting(arg1:main.UpdateSettingInput):Promise<void>;

export function UpdateUpstreamAccount(arg1:number,arg2:main.CreateUpstreamAccountInput):Promise<void>;
